library(plotly)
library(shinydashboard)
library(shinydashboardPlus)
library(shiny)
library(lubridate)
library(stringi)
library(stringr)
library(dplyr)  
library(sp)
library(ggmap)
library(leaflet)
library(htmltools)
library(rmarkdown)
library(R.utils)
library(mailR)
library(sendmailR)
library(rJava)
library(gmailr)
library(mail)

print("Pacotes carregados!")